#ifndef EVENTTYPES_H
#define EVENTTYPES_H

enum class UIEventType{
    BUTTON_CLICKED,
    TEXT_CHANGED,
    CHECKBOX_CHANGED,
    RADIO_BUTTON_CHANGED,
    DROPDOWN_CHANGED,
    SLIDER_CHANGED,
    TEXTBOX_CHANGED,
    WINDOW_CLOSED,
    WINDOW_OPENED,
    WINDOW_RESIZED,
    WINDOW_MOVED,
    WINDOW_MINIMIZED,
    WINDOW_MAXIMIZED,
};

#endif